### ISSUE TITLE
Armor weight

### ISSUE THREAD

**Issue by ADM8** [WeaponMechanics/ArmorMechanics#6]
### Description

Armor pieces have individual weights that can slow down or speed up a player depending on how heavy the armor piece or material is

### Configuration

  weight:
    helmet: 17
    chestplate: 45
    leggings: 25
    boots: 13
player-weight: 100
player-weight - armor weight = new weight which is turned into speed

**Comment by CJCrafter** [comment]
You can already slow a user down by using the `GENERIC_MOVEMENT_SPEED` attribute. [Here is the wiki](https://github.com/WeaponMechanics/ArmorMechanics/wiki/Armor#attributes). I also included this example ```yaml
  Attributes:
  - GENERIC_MAX_HEALTH 5 feet               # gain 2.5 hearts
  - GENERIC_KNOCKBACK_RESISTANCE 0.25 feet  # take 25% less knockback
  - GENERIC_MOVEMENT_SPEED -0.07 feet       # go very slow
```
