### ISSUE TITLE
Forced italic name type on all armor

### ISSUE THREAD

**Issue by Kleypex** [WeaponMechanics/ArmorMechanics#7]
### Has this issue already been reported? Did you ask for help before making this report?

- [X] I have searched the existing issues
- [X] I have asked for help

### Current Behavior

No matter what you do to try to make text of armor. Both Name and Lore.
It's forced as italic / <italic> instead of just regular <reset> text type

### Expected Behavior

It should be regular type of texts. You can decide if you want italic but it shouldn't be default and shouldn't be forced on everything.

### Steps To Reproduce

1. Default config.
2. Give yourself the different pre made armor and try it

### Frequency

100% of the time. It's locked to italic

### Version and Log

I've seen this with both 1.3.6 and newest 1.3.7

**Comment by CJCrafter** [comment]
Caused to due to conflict between adventure chat api and item lores having italics by default

**Comment by CJCrafter** [comment]
You can start your message with `<!i>` to fix the issue, but it will be automatically fixed in the next update of mechanicscore
