### ISSUE TITLE
[Suggestion] Allow adding bonus effects to itemsadder armors

### ISSUE THREAD

**Issue by BookWyrm114** [WeaponMechanics/ArmorMechanics#9]
### Description

Allow the plugin to modify itemsadder armors, so all itemsadder armors of that type will have bonus effects (Most noticeably bullet_resistance) applied. This way itemsadder users can have custom-textured armors with bullet resistance and other effects.

### Configuration

IA_Armor:
  Type: itemsadder:namespace:name

  Bonus_Effects:

    Bullet_Resistance:
      Base: <Percentage>
      Per_Weapon:
        - <WeaponTitle> <Percentage>
    Equip_Mechanics: <MechanicsSerializer>
    Dequip_Mechanics: <MechanicsSerializer>
    Damage_Mechanics: <MechanicsSerializer>

**Comment by CJCrafter** [comment]
This won't happen... Would need to add some sort of armor converter that would break compatibility with itemsadder.
